baseURL = "https://zubeyirtosun.github.io/"
defaultContentLanguage = "en"
languageCode = "en"
title = "Zübeyir Tosun"
theme = "hugo-blog-awesome"

[params]
  goToTop = true
  toc = true
  tocOpen = false

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
        [markup.tableOfContents]
                startLevel = 1 # ToC starts from H2
                endLevel = 5 # ToC ends at H4
                ordered = false # generates <ul> instead of <ol>


[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    [languages.en.params.author]
      avatar = "profile-pic.jpg"
      intro = "Zübeyir Tosun"
      name = "Zübeyir Tosun"
      description = "Burayı bir nevi bilgi depomla karışık blog tarzı bir yer halinde kullanmak istiyorum. Herhangi birinin herhangi bir blog'a girdiğinde oradaki uygulamayı tepeden tırnağa anlayacak şekilde yazmak benim bir numaralı hedefim, teşekkürler :)"


[[params.socialIcons]]
name = "github"
url = "https://github.com/zubeyirtosun"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/zubeyirtosun/"
